### ISSUE TITLE
Replace the spacing hack with CSS

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/duwamish#160]
In our "place-form" template under `src/sa_web/jstemplates/place-form.html`, ~line 94, we have a line like this:

```html
            </div>
            <!-- TODO Use custom whitespace via CSS instead of p tags -->
            <p></p>
            {{/ place_config.items }}
          </fieldset>
```

We should replace `<p></p>` with a css solution that isn't as big of a space.

**Comment by MitchLillie** [comment]
Let me know if this works for you, Luke!

**Comment by LukeSwart** [comment]
Thanks for the help, this works great! Closing this issue now :smiley:
