### ISSUE TITLE
Generate import script / schema for Georgetown neighborhood spreadsheet data

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/duwamish#180]
We got our hands on a spreadsheet with 104 records of data, each record being a project that was suggested in one of the 6 planning reports that were generated between 1977 - 2008 by and for Georgetown residents. Each record contains a project status of No, In-Progress, Dead, Complete

We need to import these as place points, and generate a nice template for contributors to format for future imports so @LukeSwart can work on other things like the admin panel  :)

Ideally our first import should take place before Nov 20th Mappy Hour, but definitely by end of November to meet our goal monthly goal for the community.

**Comment by futuresoup** [comment]
Note, that the spreadsheet needs cleaning, some of the records say "In" instead of the full phrase of "In Progress"

**Comment by LukeSwart** [comment]
This issue was completed by the scripts in our spreadsheet-muncher repo: https://github.com/smartercleanup/spreadsheet-muncher/
