### ISSUE TITLE
Green Wall request (temporary feature)

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/duwamish#191]
We need to have this live by December 2nd to be sent out to the community.

Let's ship Max's new button interface and add a new 'report type' button that says "nominate a green wall"

At first we discovered having a separate report button for the green wall, but I think this will be easier to implement if we just keep it in the normal 'submit a report' button, plus it will get people in the habit of submitting a report and get familiar with the new interface.

The form only needs to have a description field that says "add a comment about your nomination"

The pin should be a unique green leafy type icon.

---

@LukeSwart wants to have a new dataset for the green wall nominations, so we need to be able to implement multiple datasets on the same map.

Let's get the config refactored properly so I can put this together myself just by updating the config file.

cc @maxburto @twitterhandle

**Comment by futuresoup** [comment]
Currently depends on #141 unless we decide to make green wall nominations a ``place_type`` but I think a separate dataset makes more sense since it is more temporary and may be handed off later

**Comment by LukeSwart** [comment]
We are still working on the dataset (#141) and Dynamic forms (#127) , but the greenwall feature is already implemented.
