### ISSUE TITLE
optimize icon images

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/duwamish#242]
Resize with this script - http://ix.io/nW7

Save that under a file name, ie resize-pics.sh. Then make sure the file is executable: chmod +x resize-pics.sh then run it ./resize-pics.sh ...<etc>

move to duwamish flavor

**Comment by LukeSwart** [comment]
Also, that script isn't the best. I think I coded that in a pinch, ([source is here](https://github.com/LukeSwart/dotfiles/blob/master/bin/resizepics.sh)). 

If you have the ImageMagick library installed, there is a tool command called `mogrify`, which can be run like this:

```
mogrify -verbose -resize '128x128>' *.png
```
which resizes all files with the `.png` extension to 128x128 pixels. [Here is a post](https://www.webniraj.com/2013/04/07/batch-resize-images-on-linux-using-mogrify-imagemagick/) that outlines this better.

Note that these commands and libraries only apply to Linux/Mac systems.
