### ISSUE TITLE
Change the icons for submitted reports

### ISSUE THREAD

**Issue by smartercleanup** [smartercleanup/duwamish#3]
The default icons for submitted reports are blue/green buttons and are not indicative of the content.

Issue #2 suggests three report types on the report form

* Observation [icon of an eye]
* Idea [icon of a light bulb]
* Question [icon of a question mark]

**Important note:** when testing on a touch screen device, icons which are placed over a polygon are difficult to select. What happens is it selects the polygon label instead. So we'll want to test a wider area of transparency around the icon to widen the selection area and hopefully fix this...

**Comment by LukeSwart** [comment]
This issue was resolved in PR #21: https://github.com/smartercleanup/duwamish/pull/21
