### ISSUE TITLE
Enable clustering of mapbox and report points

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/duwamish#55]

**Comment by LukeSwart** [comment]
At different zoom levels, we should have different clusters to improve the visualizations

**Comment by futuresoup** [comment]
Note that we need dynamic loading in the backend so we're not hit with the "loading" screen on startup

**Comment by futuresoup** [comment]
Here is Leaflet's Markercluster repo - https://github.com/Leaflet/Leaflet.markercluster

Example here - http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

Any reason to use something other than this?
