### ISSUE TITLE
Optimize UX when submitting a report on mobile devices

### ISSUE THREAD

**Issue by smartercleanup** [smartercleanup/duwamish#7]
Preliminary tests on an iPhone 5c and some small screen Android device (forget which one) have shown that after hitting the "submit a report" button, the form is a bit hidden at the very bottom and requires scrolling to access.

Most users will probably miss this

**Comment by LukeSwart** [comment]
I think this may have been addressed in commit 11ca017
Let me know if there is still an issue, and on which devices that it is an issue. We may eventually want to re-design our mobile experience.
