### ISSUE TITLE
Place default pin to an address-generated location based on data entered by the user

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/duwamish#73]
Some users fail to grasp the map dragging prompt. We need to place a default pin based on the data that they enter into the submission form

**Comment by LukeSwart** [comment]
I think we have this implemented in our raingardens form. Should we add the address field that syncs with the map to our duwamish form?

**Comment by futuresoup** [comment]
Let's close for now. Once we do user testing we can reopen, but I think most people are not going to know the address of where they are reporting something and I want to keep the form as simple as possible.
