### ISSUE TITLE
Create and implement layer for cleanup sites

### ISSUE THREAD

**Issue by smartercleanup** [smartercleanup/duwamish#8]
Right now we have junk data on our "freehand drawings" layer. It needs to be have real polygons, labels, media, etc. that properly showcase the cleanup sites over the next few years. We are deciding if this is best done through Mapbox or GeoServer

We want to prioritize the upcoming cleanup sites, but it would also would be good to show completed sites from the past like t117 if we can in this round.

**Comment by futuresoup** [comment]
This has been created on Hey Duwamish under "Areas of Concern"

The data needs to still be drawn and updated with photos and descriptions

**Comment by futuresoup** [comment]
The 5 early action sites should be included with the paper map data laters that @LukeSwart acquired. We should try styling them in Mapbox Studio.

**Comment by LukeSwart** [comment]
I believe this is analogous to adding our community GIS layers (#195), and both of these issues are partly completed. Hopefully both will be resolved soon!

**Comment by futuresoup** [comment]
This is done, early action sites are on the map via mapbox classic
