### ISSUE TITLE
Create interactive sidebar for GIS layers

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/duwamish#89]
Here is a decent leaflet [plugin](https://github.com/Turbo87/sidebar-v2)

Though looking at the [demo](http://turbo87.github.io/sidebar-v2/examples/) page it's not perfect. The main UX issue is that there's no arrow that shows how to close it once it's open. You have to know to click the side icon again. But we can make a URL in the description page for each one that closes it, or add our own side arrows.

The other potential issue is how to integrate the activity stream with it

We could move the activity stream to the bottom perhaps and have it be its own thing

**Comment by LukeSwart** [comment]
This issue is dependent on us resolving the folding sidebar issue first: https://github.com/smartercleanup/duwamish/issues/53

Once the sidebar is folding in/out, then we can move the gis toggle buttons onto this leaflet plugin for the left side.

**Comment by futuresoup** [comment]
Not necessarily (see my comment on issue #53)

We can, (if we want), load everything as one sidebar and organize it by icon groupings along the left side of the canvas.

I think it will be simplest to try it that way for now, unless there are other opinions (?)

**Comment by LukeSwart** [comment]
Here is some work that Max did on the leaflet sidebar, if someone wants to explore where he left off: https://github.com/smartercleanup/duwamish/commit/809e6fec51dbf970afd9e7c9dfbfb4f103cedc0b

**Comment by LukeSwart** [comment]
Resolved via PR #252
